#!/usr/bin/env bash
# 1-list_your_processes
# This script lists all currently running processes in a user-oriented, hierarchical format.

ps -o user,pid,%cpu,%mem,vsz,rss,tty,stat,lstart=STARTED,time,command --forest -axww
